#
# This file generated by pbxbuild 
#

include $(GNUSTEP_MAKEFILES)/common.make

GNUSTEP_TYPE = framework
FRAMEWORK_NAME = FMTwitterKit

FMTwitterKit_CURRENT_VERSION_NAME = A

FMTwitterKit_OBJC_FILES = Source/FMTweet.m Source/FMTweetFactory.m Source/FMTwitterUser.m

FMTwitterKit_HEADER_FILES = FMTweet.h FMTweetFactory.h FMTwitterUser.h FMTwitterKit.h FMTwitterKitGlobals.h

FMTwitterKit_HEADER_FILES_DIR = Headers

FMTwitterKit_ADDITIONAL_HEADER_FILES = FMTwitterKit.h

FMTwitterKit_RESOURCE_FILES = images/bird-bigger.png images/bird-normal.png images/bird-small.png

FMTwitterKit_LOCALIZED_RESOURCE_FILES = InfoPlist.strings

FMTwitterKit_LANGUAGES = en

FMTwitterKit_INCLUDE_DIRS =  -IHeaders

FMTwitterKit_LIB_DIRS=

include $(GNUSTEP_MAKEFILES)/framework.make

CC=clang
OBJCFLAGS = -D_NATIVE_OBJC_EXCEPTIONS -fobjc-nonfragile-abi

